# Generated by Django 2.1 on 2019-05-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=200)),
                ('roastery', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('roast_levels', models.IntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Dark'), (4, 'Unknown')], default=1)),
                ('methods', models.IntegerField(choices=[(1, 'Pour Over'), (2, 'AiroPress'), (3, 'French Press'), (4, 'Drip'), (5, 'Unknown')], default=1)),
                ('stars', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3)),
                ('acidity', models.ManyToManyField(blank=True, to='brew.Acidity')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, choices=[(None, 'Country of Origin'), ('Africa', (('kenya', 'Kenya'), ('ethiopia', 'Ethiopia'), ('burundi', 'Burundi'), ('rowanda', 'Rowanda'), ('other_africa', 'Other Africa'))), ('Central America', (('costa_rica', 'Costa Rica'), ('el_salvado', 'El Salvador'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('panama', 'Panama'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'))), ('South America', (('brazil', 'Brazil'), ('bolivia', 'Bolivia'), ('colombia', 'Colombia'))), ('Far East', (('bali', 'Bali'), ('papua_new-guinea', 'Papua New Guinea'), ('sumatra', 'Sumatra'), ('thailand', 'Thailand'), ('java', 'Java'), ('myanmar', 'Mayanmar'), ('vietnam', 'Vietnam')))], max_length=50, null=True)),
                ('roast_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('batch_size', models.CharField(blank=True, max_length=20, null=True)),
                ('roast_time', models.CharField(blank=True, max_length=20, null=True)),
                ('roast_levels', models.IntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Dark'), (4, 'Unknown')], default=1)),
                ('first_crack_start', models.CharField(blank=True, max_length=20, null=True)),
                ('first_crack_end', models.CharField(blank=True, max_length=20, null=True)),
                ('second_crack_start', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='flavor',
            field=models.ManyToManyField(blank=True, to='brew.Flavor'),
        ),
        migrations.AddField(
            model_name='brew',
            name='home_roast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brew.Roast'),
        ),
        migrations.AddField(
            model_name='brew',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
