# Generated by Django 3.0.dev20190414141414 on 2019-04-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_level', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Brew')),
            ],
        ),
    ]
