# Generated by Django 2.1 on 2019-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='methods',
            field=models.IntegerField(choices=[(1, 'Pour Over'), (2, 'Aero Press'), (3, 'French Press'), (4, 'Drip'), (5, 'Unknown')], default=1),
        ),
    ]
