# Generated by Django 3.0.dev20190414141414 on 2019-04-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_auto_20190418_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='method',
            field=models.CharField(default='Pour Over', max_length=200),
        ),
        migrations.AddField(
            model_name='brew',
            name='roast_level',
            field=models.CharField(default='Light', max_length=200),
        ),
        migrations.AddField(
            model_name='brew',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
