# Generated by Django 3.0.dev20190414141414 on 2019-04-18 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20190418_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='rates',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='brew',
            name='method',
            field=models.IntegerField(choices=[(1, 'Pour Over'), (2, 'AiroPress'), (3, 'French Press')], null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='roast_levels',
            field=models.IntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Dark')], null=True),
        ),
    ]
