# Generated by Django 3.0.dev20190414141414 on 2019-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_auto_20190418_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='method',
            field=models.IntegerField(choices=[(1, 'Pour_Over'), (2, 'AiroPress'), (3, 'French_Press')], null=True),
        ),
    ]
