# Generated by Django 3.0.dev20190414141414 on 2019-04-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_auto_20190418_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='brew',
        ),
        migrations.DeleteModel(
            name='Brew',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
