# Generated by Django 3.0.dev20190414141414 on 2019-04-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0008_brew_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='methods',
            field=models.IntegerField(blank=True, choices=[(1, 'Pour_Over'), (2, 'AiroPress'), (3, 'French_Press')], null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='roast_levels',
            field=models.IntegerField(blank=True, choices=[(1, 'Light'), (2, 'Medium'), (3, 'Dark')], null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
