# Generated by Django 3.0.dev20190414141414 on 2019-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0012_auto_20190422_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(blank=True, default=0, null=True)),
                ('roast_name', models.CharField(max_length=200)),
                ('batch_size', models.CharField(max_length=200)),
                ('roast_time', models.TimeField(max_length=20)),
                ('roast_levels', models.IntegerField(blank=True, default=1, null=True)),
                ('first_crack_start', models.TimeField(max_length=20)),
                ('first_crack_end', models.TimeField(max_length=20)),
                ('second_crack_start', models.TimeField(max_length=20)),
                ('notes', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='roastery',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
