# Generated by Django 3.0.dev20190414141414 on 2019-04-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0013_auto_20190430_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='home_roast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brew.Roast'),
        ),
    ]
