# Generated by Django 3.0.dev20190414141414 on 2019-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0014_brew_home_roast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='acidity',
            field=models.IntegerField(blank=True, choices=[(None, 'Taste like Coffee'), (1, 'Mellow'), (2, 'Winey'), (3, 'Citrus'), (4, 'Sour'), (5, 'Berry-like')], null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='flavor',
            field=models.IntegerField(blank=True, choices=[(None, 'Taste like Coffee'), (1, 'Fruity'), (2, 'Sweet'), (3, 'Nutty'), (4, 'Woody'), (5, 'Malty')], null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='methods',
            field=models.IntegerField(choices=[(1, 'Pour Over'), (2, 'AiroPress'), (3, 'French Press'), (4, 'Drip'), (5, 'Unknown')], default=1),
        ),
        migrations.AlterField(
            model_name='roast',
            name='origin',
            field=models.CharField(blank=True, choices=[(None, 'Country of Origin'), ('Africa', (('kenya', 'Kenya'), ('ethiopia', 'Ethiopia'), ('burundi', 'Burundi'), ('rowanda', 'Rowanda'), ('other_africa', 'Other Africa'))), ('Central America', (('costa_rica', 'Costa Rica'), ('el_salvado', 'El Salvador'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('panama', 'Panama'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'))), ('South America', (('brazil', 'Brazil'), ('bolivia', 'Bolivia'), ('colombia', 'Colombia'))), ('Far East', (('bali', 'Bali'), ('papua_new-guinea', 'Papua New Guinea'), ('sumatra', 'Sumatra'), ('thailand', 'Thailand'), ('java', 'Java'), ('myanmar', 'Mayanmar'), ('vietnam', 'Vietnam')))], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roast',
            name='roast_levels',
            field=models.IntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Dark'), (4, 'Unknown')], default=1),
        ),
    ]
