# Generated by Django 3.0.dev20190414141414 on 2019-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0016_auto_20190504_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='brew',
            name='flavor',
        ),
        migrations.AddField(
            model_name='brew',
            name='flavor',
            field=models.ManyToManyField(to='brew.Flavor'),
        ),
    ]
