# Generated by Django 3.0.dev20190414141414 on 2019-05-04 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brew', '0017_auto_20190504_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brew',
            name='acidity',
            field=models.ManyToManyField(blank=True, to='brew.Acidity'),
        ),
        migrations.AlterField(
            model_name='brew',
            name='flavor',
            field=models.ManyToManyField(blank=True, to='brew.Flavor'),
        ),
    ]
