# Generated by Django 3.0.dev20190414141414 on 2019-05-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0019_auto_20190504_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
