# Generated by Django 3.0.dev20190414141414 on 2019-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0020_auto_20190506_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='stars',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=1),
        ),
    ]
