# Generated by Django 3.0.dev20190414141414 on 2019-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0021_brew_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='stars',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3),
        ),
    ]
